name: build

on: [push, pull_request]

env:
    DEFAULT_COMPOSER_FLAGS: "--prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi"

jobs:
    phpunit:
        name: PHP ${{ matrix.php }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: ['8.2', '8.3']

        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - run: rm -rf composer.lock
            - run: composer install

            - run: vendor/bin/phpunit --verbose --colors=always
